name: stable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build & Push:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}

    - name: Build OctoPetShop web container
      run: |
        docker build ./OctopusSamples.OctoPetShop.Web --file ./OctopusSamples.OctoPetShop.Web/dockerfile --tag octopussamples/octopetshop-web-ndc:$PACKAGE_VERSION
        docker push octopussamples/octopetshop-web-ndc:$PACKAGE_VERSION
        
    - name: Build OctoPetShop product service container
      run: | 
        docker build ./OctopusSamples.OctoPetShop.ProductService --file ./OctopusSamples.OctoPetShop.ProductService/dockerfile --tag octopussamples/octopetshop-productservice-ndc:$PACKAGE_VERSION
        docker push octopussamples/octopetshop-productservice-ndc:$PACKAGE_VERSION
        
    - name: Build OctoPetShop shopping cart container
      run: | 
        docker build ./OctopusSamples.OctoPetShop.ShoppingCartService --file ./OctopusSamples.OctoPetShop.ShoppingCartService/dockerfile --tag octopussamples/octopetshop-shoppingcartservice-ndc:$PACKAGE_VERSION
        docker push octopussamples/octopetshop-shoppingcartservice-ndc:$PACKAGE_VERSION
        
    - name: Build OctoPetShop database container
      run: | 
        docker build ./OctopusSamples.OctoPetShop.Database --file ./OctopusSamples.OctoPetShop.Database/dockerfile --tag octopussamples/octopetshop-database-ndc:$PACKAGE_VERSION
        docker push octopussamples/octopetshop-database-ndc:$PACKAGE_VERSION

  Deploy:

    runs-on: ubuntu-latest
    
    - name: Push build information
      uses: OctopusDeploy/push-build-information-action@v3
      with:
        packages: |
          octopussamples/octopetshop-web-ndc
          octopussamples/octopetshop-productservice-ndc
          octopussamples/octopetshop-shoppingcartservice-ndc
          octopussamples/octopetshop-database-ndc
        version: ${{ env.PACKAGE_VERSION }}
        
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v3
      with:
        version: latest

    - name: Create OctoPetShop release
      uses: OctopusDeploy/create-release-action@v3
      with:
        project: OctoPetShop
        git_ref: main
        
        
        
 
